POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxpbHlldmFucyIsImlkIjoiNjE0ZWU2YTM0MDk1YzE1OGVmZjZmNzE2IiwiaWF0IjoxNjMyNTYwODA4fQ.iad0NR_7MX9zmVTPqyD5iZ6ZZHcWfHpQ-W1U0i6Xo3Q

{
    "title": "Fried Potatoes",
    "author": "Crunchy",
    "url": "www.friedpotatoes.com",
    "likes": 10
}
