name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
      PORT: ${{ secrets.PORT }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn eslint
      - name: build
        run: yarn build
      - name: test
        uses: cypress-io/github-action@v2
        with:
          command: yarn test
          start: yarn start:test
          wait-on: http://localhost:${{ secrets.PORT }}
